run:
  tests: false
  timeout: 3m
linters:
  enable-all: true
  disable:
    - wsl
linters-settings:
  errcheck:
    check-type-assertions: true
  golint:
    min-confidence: 0
  gocyclo:
    min-complexity: 20
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2
  misspell:
    locale: UK
  lll:
    line-length: 160
  funlen:
    lines: 150
    statements: 100
issues:
  exclude-rules:
    - text: "`.*Regex` is a global variable"
      linters:
        - gochecknoglobals
    - text: "weak cryptographic primitive"
      path: pkg/versions/install.go
      linters:
        - gosec
    - text: "`wrappedCmd` is a global variable"
      path: cmd/generic-cmd-wrapper/main.go
      linters:
        - gochecknoglobals
