language: go

go:
  - 1.14.x

before_install:
  - "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.26.0"

deploy:
  - provider: script
    script: GOOS=linux GOARCH=amd64 make clean bin
    on:
      branch: test
  - provider: script
    script: GOOS=windows GOARCH=amd64 make clean bin
    on:
      branch: test
  - provider: script
    script: GOOS=darwin GOARCH=amd64 make clean bin
    on:
      branch: test
