package versionsfile

type GoArchive struct {
	OS     string
	ARCH   string
	URL    string
	SHA256 string
}

// RemoteVersionsFile is the representation of the file that gets stored in
// GitHub. That file is pregenerated by parsing go downloads page.
type RemoteVersionsFile struct {
	versions map[string][]GoArchive
}

// GetArchivesFor available archives indexed by version for the provided CPU
// architecture and OS.
func (rvf *RemoteVersionsFile) GetArchivesFor(arch, os string) map[string]GoArchive {
	foundArchives := make(map[string]GoArchive)
	for version, archives := range rvf.versions {
		for _, archive := range archives {
			if archive.ARCH == arch && archive.OS == os {
				foundArchives[version] = archive
				break
			}
		}
	}

	return foundArchives
}
