name: generate-versions-file

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Generate versions file
        run: make generate-versions-file

      - id: check-versions-file
        name: Check if changes in versions file
        run: git diff-index HEAD data/versions.json
        continue-on-error: true

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Generate Versions File Action"
          git add data/versions.json
          git commit -m "new versions file $(date +%F)"
        if: ${{ steps.check-versions-file.outcome == "failure" }}

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
        if: ${{ steps.check-versions-file.outcome == "failure" }}
