name: generate-versions-file

on:
  schedule:
    - cron: '10 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Unshallow
        run: git fetch --prune --unshallow

      - name: Generate versions file
        run: make generate-versions-file

      - id: check-versions-file
        name: Check if changes in versions file
        run: git diff-index --exit-code HEAD data/versions.json
        continue-on-error: true

      - name: Commit files
        run: |
          git config --local user.email "${{ github.actor }}@users.noreply.github.com"
          git config --local user.name "Generate Versions File - ${{ github.actor }}"
          git checkout -b new-versions-$(date +%F)
          git add data/versions.json
          git commit -m "new versions file $(date +%F) [skip ci]"
        if: "steps.check-versions-file.outcome == 'failure'"

      - name: Push changes
        run: |
          curl -fsSL https://github.com/github/hub/raw/master/script/get | bash -s 2.14.1
          hub pull-request -p --no-edit --labels versions
          bin/hub pr list  # list pull requests in the current repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: "steps.check-versions-file.outcome == 'failure'"